version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/stac_fastapi/mongo"
    schedule:
      interval: daily
