version: '3.9'

services:
  stac-browser:
    container_name: stac-browser
    image: ghcr.io/radiantearth/stac-browser:latest
    ports:
      - 8080:8080
    environment:
      SB_catalogUrl: "http://localhost:8084"

  app-mongo:
    container_name: stac-fastapi-mongo
    image: stac-utils/stac-fastapi-mongo
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev.mongo
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8084
      - RELOAD=true
      - ENVIRONMENT=local
      - BACKEND=mongo
      - MONGO_DB=TUBIN
      - MONGO_HOST=tubix20.space.tu-berlin.de
      - MONGO_USER=guest
      - MONGO_PASS=4m5076CHbL7QK4NL
      - MONGO_PORT=27017
      - STAC_COLLECTIONS_INDEX=stac_collections
      - STAC_ITEMS_INDEX=fm.georef.files
      - STAC_FILES_BUCKET=fm.georef
      - MONGO_CREATE_INDEXES=false # if true (or missing), creates collections and items indexes in the MongoDB at startup
    ports:
      - "8084:8084"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
    command:
      bash -c "python -m stac_fastapi.mongo.app"
